# Site settings
title: RDMLA
email: rdmla.help@gmail.com
description: >
 Research Data Management Librarian Academy (RDMLA): Exploring and providing research data management training for librarians.
url: "https://rdmla.github.io/"

# Social links
github_username:  RDMLA
twitter_username: The_RDMLA
facebook_username: TheRDMLA

# Build settings
markdown: kramdown
theme: minima

# plugins
plugins:
  - jekyll-redirect-from
